package com.partenaires.resanet.hotel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-12-07T02:29:00.095+01:00
 * Generated source version: 2.3.2
 * 
 */
 
@WebService(targetNamespace = "http://www.resanet.partenaires.com/hotel", name = "hotelEndPoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HotelEndPoint {

    @WebResult(name = "rechercherHotelResponse", targetNamespace = "http://www.resanet.partenaires.com/hotel", partName = "out")
    @WebMethod
    public RechercherHotelResponse rechercherHotel(
        @WebParam(partName = "in", name = "rechercherHotelRequest", targetNamespace = "http://www.resanet.partenaires.com/hotel")
        RechercherHotelRequest in
    ) throws RechercherHotelFault;
}
