
package com.partenaires.resanet.hotel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2012-12-07T02:29:00.066+01:00
 * Generated source version: 2.3.2
 * 
 */

@WebFault(name = "rechercherHotelFault", targetNamespace = "http://www.resanet.partenaires.com/hotel")
public class RechercherHotelFault extends Exception {
    public static final long serialVersionUID = 20121207022900L;
    
    private java.lang.String rechercherHotelFault;

    public RechercherHotelFault() {
        super();
    }
    
    public RechercherHotelFault(String message) {
        super(message);
    }
    
    public RechercherHotelFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RechercherHotelFault(String message, java.lang.String rechercherHotelFault) {
        super(message);
        this.rechercherHotelFault = rechercherHotelFault;
    }

    public RechercherHotelFault(String message, java.lang.String rechercherHotelFault, Throwable cause) {
        super(message, cause);
        this.rechercherHotelFault = rechercherHotelFault;
    }

    public java.lang.String getFaultInfo() {
        return this.rechercherHotelFault;
    }
}
